In [1]:
pip install pandas numpy yfinance matplotlib

Requirement already satisfied: pandas in c:\users\dell\anaconda3\lib\site-packages (2.2.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy in c:\users\dell\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied: yfinance in c:\users\dell\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: matplotlib in c:\users\dell\anaconda3\lib\site-packages (3.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: requests>=2.31 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (4.3.7)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (4.0.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in c:\users\dell\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\dell\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2025.4.26)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\dell\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: pycparser in c:\users\dell\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.21)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dell\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.3.0)

In [13]:
import pandas as pd
import numpy as np
import yfinance as yf

In [14]:
sp500 = yf.download("^GSPC", start="2020-01-01", end="2024-01-01")

sp500 = sp500.reset_index()

sp500.head()

[*********************100%***********************]  1 of 1 completed

Price,Date,Close,High,Low,Open,Volume
Ticker,,^GSPC,^GSPC,^GSPC,^GSPC,^GSPC
0,2020-01-02,3257.850098,3258.139893,3235.530029,3244.669922,3459930000
1,2020-01-03,3234.850098,3246.149902,3222.340088,3226.360107,3484700000
2,2020-01-06,3246.280029,3246.840088,3214.639893,3217.550049,3702460000
3,2020-01-07,3237.179932,3244.909912,3232.429932,3241.860107,3435910000
4,2020-01-08,3253.050049,3267.070068,3236.669922,3238.590088,3726840000

In [15]:
data = pd.DataFrame()

data["Date"] = sp500["Date"]

data["Momentum"] = sp500["Close"].pct_change(20)

data["Volatility"] = sp500["Close"].rolling(20).std()

data["Strength"] = np.where(
    sp500["Close"] > sp500["Close"].rolling(50).mean(),
    1,
    0
)

data.head()

        Date  Momentum  Volatility  Strength
0 2020-01-02       NaN         NaN         0
1 2020-01-03       NaN         NaN         0
2 2020-01-06       NaN         NaN         0
3 2020-01-07       NaN         NaN         0
4 2020-01-08       NaN         NaN         0

In [16]:
np.random.seed(42)

data["Safe_Haven"] = np.random.normal(0,0.01,len(data))

data["Put_Call"] = np.random.uniform(0.8,1.2,len(data))

data["Breadth"] = np.random.uniform(0,1,len(data))

data.head()

        Date  Momentum  Volatility  Strength  Safe_Haven  Put_Call   Breadth
0 2020-01-02       NaN         NaN         0    0.004967  1.085635  0.493547
1 2020-01-03       NaN         NaN         0   -0.001383  1.120691  0.702259
2 2020-01-06       NaN         NaN         0    0.006477  0.935780  0.992817
3 2020-01-07       NaN         NaN         0    0.015230  1.125930  0.131489
4 2020-01-08       NaN         NaN         0   -0.002342  0.832046  0.274732

In [17]:
data = data.fillna(method="bfill")

data.shape

C:\Users\DELL\AppData\Local\Temp\ipykernel_11792\3609870751.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data = data.fillna(method="bfill")

(1006, 7)

In [18]:
data["Fear_Greed_Index"] = (
    data["Momentum"]*25
    - data["Volatility"]*25
    + data["Strength"]*15
    - data["Safe_Haven"]*10
    - data["Put_Call"]*10
    + data["Breadth"]*15
)

In [19]:
data["Fear_Greed_Index"] = (
    (data["Fear_Greed_Index"] - data["Fear_Greed_Index"].min())
    /
    (data["Fear_Greed_Index"].max() - data["Fear_Greed_Index"].min())
)*100

data.shape

(1006, 8)

In [20]:
data.to_csv("../data/fear_greed_index.csv", index=False)

print("CSV saved successfully")

CSV saved successfully